# Generated by Django 3.2.5 on 2021-07-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_auto_20210701_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='user_name',
            field=models.CharField(default='null', editable=False, max_length=250),
        ),
    ]
